"""Parley voice gateway — an OpenAI-compatible endpoint that IS the agent's brain.

ElevenLabs' "Custom LLM" mode calls a `POST /v1/chat/completions` (SSE streaming) server and
speaks whatever it streams back. So we register THIS as the model: every word the phone agent
utters is generated by Parley's code, not by a free-running LLM. That's the whole point — a
commitment can only be spoken after it clears the owner's sheet in code (`sheet.evaluate`), and a
refusal is masked (see `voice/policy.py`). The LLM never gets a "just agree" branch.

Pipeline per turn:
    counterparty speech (last user message) -> extract a concrete option -> sheet.evaluate(option)
    -> policy.reply_for(evaluation) -> stream that (masked) line as the model's reply.

Zero new deps: stdlib http.server + SSE. Anthropic/eleven keys are NOT needed to run or test this
deterministically; the natural-language extractor is pluggable (a Claude extractor drops in behind
an optional extra later — this MVP ships a fail-closed structured extractor).

Run (from the repo root, so the `voice` package resolves):
      PARLEY_GATEWAY_BEARER=dev PARLEY_VOICE_RECIPE=examples/demo/recipe_estate.json \
      PARLEY_VOICE_OWNER="Heir 2" python -m voice.gateway
"""
import json
import os
import re
import time
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer

from parley.spec import DecisionSpec

MAX_BODY = 64 * 1024  # bound the request body (same discipline as parley/net/bot.py)


def extract_option(messages: list) -> dict | None:
    """Pin the counterparty's last turn to a concrete option dict, or None (fail-closed).

    MVP extractor: reads the last user message and accepts either an embedded JSON object or
    `key=value` tokens (numbers/bools coerced). Natural-language speech that doesn't pin to a
    concrete option returns None -> the agent asks to clarify rather than inventing agreement.
    A Claude-backed extractor (NL -> option) replaces this behind an optional extra; the contract
    (str -> dict|None, fail-closed) stays identical.
    """
    text = ""
    for m in reversed(messages):
        if m.get("role") == "user":
            text = m.get("content") or ""
            break
    if not text:
        return None
    # 1) an embedded JSON object
    brace = re.search(r"\{.*\}", text, re.DOTALL)
    if brace:
        try:
            got = json.loads(brace.group(0))
            if isinstance(got, dict) and got:
                return got
        except ValueError:
            pass
    # 2) key=value tokens
    pairs = re.findall(r"([A-Za-z_][\w]*)\s*=\s*([^\s,;]+)", text)
    if pairs:
        return {k: _coerce(v) for k, v in pairs}
    return None


def _coerce(v: str):
    low = v.lower()
    if low in ("true", "false"):
        return low == "true"
    try:
        return int(v)
    except ValueError:
        try:
            return float(v)
        except ValueError:
            return v


class _Gateway:
    """Holds the owner's private sheet — loaded once from the recipe, never sent anywhere."""

    def __init__(self, recipe_path: str, owner: str):
        spec = DecisionSpec.load(recipe_path)
        match = [p for p in spec.parties if p.owner == owner]
        if not match:
            raise ValueError(f"owner {owner!r} not in recipe; parties: {[p.owner for p in spec.parties]}")
        self.owner = owner
        self.sheet = match[0].to_sheet()   # the private red lines + utility — code, not the LLM
        self.options = spec.options        # PUBLIC options (the coordinator sees these) — safe context
        # Use Claude (via OpenRouter) as the brain for live conversation when a key is present;
        # else the deterministic structured extractor (tests + no-key local runs). Either way the
        # sheet decides: the brain only ever gets a masked consider_option result.
        self.use_brain = bool(os.environ.get("OPENROUTER_API_KEY"))

    def decide_reply(self, messages: list) -> str:
        if self.use_brain:
            from voice import brain
            return brain.respond(messages, self.sheet, options_hint=self.options)
        from voice.policy import reply_for
        option = extract_option(messages)
        ev = self.sheet.evaluate(option) if option is not None else None
        return reply_for(ev)


def _sse_chunks(reply: str):
    """OpenAI chat.completion.chunk SSE frames: one content delta, a stop, then [DONE]."""
    cid = f"chatcmpl-parley-{int(time.time()*1000)}"
    base = {"id": cid, "object": "chat.completion.chunk", "model": "parley-voice"}
    yield _frame({**base, "choices": [{"index": 0, "delta": {"role": "assistant", "content": reply}, "finish_reason": None}]})
    yield _frame({**base, "choices": [{"index": 0, "delta": {}, "finish_reason": "stop"}]})
    yield "data: [DONE]\n\n"


def _frame(obj: dict) -> str:
    return "data: " + json.dumps(obj) + "\n\n"


def make_handler(gateway: "_Gateway", bearer: str | None):
    class _Handler(BaseHTTPRequestHandler):
        def log_message(self, *a):
            pass

        def _unauthorized(self):
            self.send_response(401)
            self.send_header("Content-Type", "application/json")
            self.end_headers()
            self.wfile.write(b'{"error":"unauthorized"}')

        def do_POST(self):
            if self.path.rstrip("/") != "/v1/chat/completions":
                self.send_response(404)
                self.end_headers()
                return
            if bearer:
                got = self.headers.get("Authorization", "")
                if got != f"Bearer {bearer}":
                    return self._unauthorized()
            length = int(self.headers.get("Content-Length") or 0)
            if length <= 0 or length > MAX_BODY:
                self.send_response(413)
                self.end_headers()
                return
            try:
                payload = json.loads(self.rfile.read(length))
                messages = payload["messages"]
                assert isinstance(messages, list)
            except (ValueError, KeyError, AssertionError):
                self.send_response(400)
                self.end_headers()
                return
            reply = gateway.decide_reply(messages)
            self.send_response(200)
            self.send_header("Content-Type", "text/event-stream")
            self.send_header("Cache-Control", "no-cache")
            self.end_headers()
            for chunk in _sse_chunks(reply):
                self.wfile.write(chunk.encode("utf-8"))
                self.wfile.flush()

    return _Handler


def serve(recipe_path: str, owner: str, bearer: str | None, host="127.0.0.1", port=8013):
    gateway = _Gateway(recipe_path, owner)
    httpd = ThreadingHTTPServer((host, port), make_handler(gateway, bearer))
    print(f"[parley voice] http://{host}:{port}/v1/chat/completions  owner={owner!r}  (Ctrl-C to stop)", flush=True)
    return httpd


if __name__ == "__main__":
    recipe = os.environ.get("PARLEY_VOICE_RECIPE", "examples/demo/recipe_estate.json")
    owner = os.environ.get("PARLEY_VOICE_OWNER", "Heir 2")
    bearer = os.environ.get("PARLEY_GATEWAY_BEARER")
    host, port = os.environ.get("PARLEY_HOST", "127.0.0.1"), int(os.environ.get("PARLEY_PORT", "8013"))
    serve(recipe, owner, bearer, host, port).serve_forever()
